### PR TITLE
Implement pruning for postgres

### PR DESCRIPTION
**Pull request by A5308Y**

### CODE REVIEW

**Comment by A5308Y** [comment]
@rmehner sagt:
> - Warum verlassen wir uns auf eine Env Variable die da sein muss (und nirgendwo dokumentiert ist)
Ich hatte für meinen act user mal keine Rechte andere Datenbanken zu sehen.
> - Warum nehmen wir nicht Active Record Connection, die wir ja eh nutzen an anderer Stelle? (im Load Task)
Wohl aus dem gleichen Grund.

Ich glaube allerdings, dass ich das ändern musste und act jetzt superuser ist. Dann sollte beides wahrscheinlich gehen. Und dann wär' das natürlich schöner.

**Comment by rmehner** [comment]
I think for a dev tool like this, it's okay to assume that the database user in `database.yml` for development is allowed to create / delete databases. Especially since we're already assuming that during the `load` task.

**Comment by rmehner** [comment]
> I think for a dev tool like this, it's okay to assume that the database user in `database.yml` for development is allowed to create / delete databases. Especially since we're already assuming that during the `load` task

What we can do is to rescue the Exception that raises once the deletion/creation fails and have a good error message for those.

**Comment by A5308Y** [comment]
> What we can do is to rescue the Exception that raises once the deletion/creation fails and have a good error message for those.

I already had already added it to the readme. I'm Ok with it like it is for now.

**Comment by A5308Y** [comment]
@rmehner @malfynnction

**Review by malfynnction — APPROVED** [review]

**Pull request merged**
